name: Daily Green Streak

on:
  schedule:
    - cron: '35 18 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # This ensures we pull the latest history
          fetch-depth: 0

      - name: Update Streak File
        run: |
          # Adding a random number ensures the file is ALWAYS different
          echo "Last contribution: $(date) - ID: $RANDOM" >> streak.txt

      - name: Commit and Push
        run: |
          git config --global user.name "AkshayKatla"
          git config --global user.email "akshaykumarkatla@gmail.com"
          git add streak.txt
          
          # This check prevents the script from failing if there's nothing to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: daily streak update $(date)"
            git push origin main
          fi
